AppBundle\Entity\PioneerparkRentRecord:
    type: entity
    table: pioneerpark_rent_record
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 用户UID
        merchantId:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 商户ID
            column: merchant_id
        total:
            type: float
            nullable: false
            precision: 9
            scale: 2
            options:
                comment: 金额
        remarks:
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
                comment: 详情备注
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: '状态 0. 待支付 1. 已支付 2. 已失效'
        createAt:
            type: datetime
            nullable: false
            options:
                comment: 创建时间
            column: create_at
        completion:
            type: datetime
            nullable: false
            options:
                comment: 完成时间
    lifecycleCallbacks: {  }
