AppBundle\Entity\PioneerparkArticle:
    type: entity
    table: pioneerpark_article
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: '属性 商户 MERCHANT  东南亚专题 SOUTHEAST  合作需求 COOPERATION'
        cate:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 分类ID
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 标题
        subtitle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 子标题
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 文章内容
        thumbnail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 缩略图
        isdisplay:
            type: boolean
            nullable: false
            options:
                unsigned: false
                comment: 是否显示
        visit:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 访问量
        createAt:
            type: datetime
            nullable: false
            options:
                comment: 创建时间
            column: create_at
    lifecycleCallbacks: {  }
