AppBundle\Entity\PioneerparkDongtaiCategory:
    type: entity
    table: pioneerpark_dongtai_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                comment: 分类名称
        sort:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 排序
    lifecycleCallbacks: {  }
