AppBundle\Entity\PioneerparkXuqiuWenzhang:
    type: entity
    table: pioneerpark_xuqiu_wenzhang
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cate:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 分类ID
        mid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 企业ID
        uid:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 用户UID
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 文章标题
        subtitle:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 文章副标题
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 内容
        picture:
            type: string
            nullable: false
            length: 1000
            options:
                fixed: false
                comment: 文章图片
        thumbnail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 缩略图
        isquality:
            type: boolean
            nullable: false
            options:
                comment: 是否优质
        isrecommend:
            type: boolean
            nullable: false
            options:
                comment: 是否推荐
        contacts:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                comment: 联系人
        tel:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                comment: 联系电话
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 状态
        createAt:
            type: datetime
            nullable: false
            options:
                comment: 创建时间
            column: create_at
    lifecycleCallbacks: {  }
