AppBundle\Entity\PioneerparkNotice:
    type: entity
    table: pioneerpark_notice
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: id
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 标题
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 内容
        picture:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
                comment: 图片
        createAt:
            type: datetime
            nullable: false
            options:
                comment: 创建时间
            column: create_at
    lifecycleCallbacks: {  }
